# Generated by Django 3.2.12 on 2023-05-19 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('include_adult', models.BooleanField()),
                ('with_genres', models.TextField()),
                ('without_genres', models.TextField()),
                ('language', models.CharField(max_length=20)),
                ('with_keywords', models.TextField()),
                ('without_keywords', models.TextField()),
                ('vote_average_gte', models.FloatField()),
                ('vote_average_lte', models.FloatField()),
                ('release_year', models.IntegerField()),
                ('release_date_gte', models.DateTimeField()),
                ('release_date_lte', models.DateTimeField()),
                ('with_runtime_gte', models.IntegerField()),
                ('with_runtime_lte', models.IntegerField()),
                ('sort_by', models.CharField(max_length=50)),
                ('with_crew', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('queries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='themes.query')),
                ('theme_likes', models.ManyToManyField(related_name='like_themes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
