# Generated by Django 3.2.12 on 2023-05-19 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='queries',
        ),
        migrations.AddField(
            model_name='query',
            name='themes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='themes.theme'),
            preserve_default=False,
        ),
    ]
