# Generated by Django 3.2.12 on 2023-05-19 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0002_auto_20230519_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='include_adult',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='language',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='release_date_gte',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='release_date_lte',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='release_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='sort_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='vote_average_gte',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='vote_average_lte',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='with_crew',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='with_genres',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='with_keywords',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='with_runtime_gte',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='with_runtime_lte',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='without_genres',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='without_keywords',
            field=models.TextField(null=True),
        ),
    ]
