# Generated by Django 3.2.12 on 2023-05-19 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0003_auto_20230519_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='themes',
            new_name='theme',
        ),
    ]
