# Generated by Django 3.2.12 on 2023-05-22 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0007_alter_query_include_adult'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('include_adult', models.CharField(max_length=10, null=True)),
                ('with_genres', models.TextField(null=True)),
                ('without_genres', models.TextField(null=True)),
                ('language', models.CharField(max_length=20, null=True)),
                ('with_keywords', models.TextField(null=True)),
                ('without_keywords', models.TextField(null=True)),
                ('vote_average_gte', models.FloatField(null=True)),
                ('vote_average_lte', models.FloatField(null=True)),
                ('release_year', models.IntegerField(null=True)),
                ('release_date_gte', models.DateTimeField(null=True)),
                ('release_date_lte', models.DateTimeField(null=True)),
                ('with_runtime_gte', models.IntegerField(null=True)),
                ('with_runtime_lte', models.IntegerField(null=True)),
                ('sort_by', models.CharField(max_length=50, null=True)),
                ('with_crew', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='theme',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Query',
        ),
        migrations.AddField(
            model_name='question',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='themes.theme'),
        ),
        migrations.AddField(
            model_name='answerquery',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='themes.question'),
        ),
    ]
