# Generated by Django 3.2.12 on 2023-05-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0008_auto_20230522_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
