# Generated by Django 3.2.12 on 2023-05-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0009_alter_theme_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerquery',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
