# Generated by Django 3.2.12 on 2023-05-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_movie_backdrop_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tagline',
            field=models.TextField(null=True),
        ),
    ]
